### ISSUE TITLE
Error when training/testing on COCO dataset

### ISSUE THREAD

**Issue by Poeroz** [leoxiaobin/deep-high-resolution-net.pytorch#133]
My problem is similar to #100 , but I have tried all possible solutions in that issue and still can not solve the problem...

Now I want to training/testing on COCO dataset, and visualize the model by using tensorboardX. Unfortunately, errors occurred one by one... At first, I met the same problem as [this](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/100#issue-483495799), then I downgrade my tensorboardX version to 1.6, and met the same problem as [this](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/100#issuecomment-540992942), then I tried to degrade other package like torch, torchvision, etc., but it didn't work as well.

Currently my version is as follows:
```
torch 1.0.0
torchvision 0.2.1
tensorboard 1.6.0
tensorboardX 1.6
tensorflow 1.0.0
cudatoolkit 9.0
```
When I want to start training using the following command:
```
python tools/train.py --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3_coco2014.yaml
```
It tells me:
```
RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 1; 11.93 GiB total capacity; 2.48 GiB already allocated; 2.81 MiB free; 5.46 MiB cached)
```
It seems that the part to do with tensorboardX is successfully completed, and error occurred when begin training. What I want to know is that: **Is this problem really caused by the memory of CUDA?Or it is caused by the old version of pytorch? Any code need to modified?**

And I also add the following codes into test.py, in order to visualize the model by using tensorboardX.

```
    writer_dict = {
        'writer': SummaryWriter(log_dir=tb_log_dir),
        'train_global_steps': 0,
        'valid_global_steps': 0,
    }
    dump_input = torch.rand(
        (1, 3, cfg.MODEL.IMAGE_SIZE[1], cfg.MODEL.IMAGE_SIZE[0])
    )
    writer_dict['writer'].add_graph(model, (dump_input, ))
```
When I use the following command to test...
```
python tools/test.py --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3_coco2014.yaml TEST.MODEL_FILE models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth TEST.USE_GT_BBOX False
```
The error to do with tensorboardX occurred again!
```
/home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "tools/test.py", line 142, in <module>
    main()
  File "tools/test.py", line 110, in main
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "/home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/tensorboardX/writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 235, in graph
    _optimize_trace(trace, torch.onnx.utils.OperatorExportTypes.ONNX)
  File "/home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 175, in _optimize_trace
    trace.set_graph(_optimize_graph(trace.graph(), operator_export_type))
  File "/home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 201, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple appears in op that does not forward tuples (VisitNode at /opt/conda/conda-bld/pytorch_1544174967633/work/torch/csrc/jit/passes/lower_tuples.cpp:109)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fc59951fcc5 in /home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x6d6882 (0x7fc596bf0882 in /home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #2: <unknown function> + 0x6d6ad4 (0x7fc596bf0ad4 in /home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #3: torch::jit::LowerAllTuples(std::shared_ptr<torch::jit::Graph>&) + 0x13 (0x7fc596bf0be3 in /home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x350b24 (0x7fc5c99fbb24 in /home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x111e36 (0x7fc5c97bce36 in /home/fangqingkai/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #35: __libc_start_main + 0xf0 (0x7fc5db560830 in /lib/x86_64-linux-gnu/libc.so.6)
```

It confused me that why the same code has not caused error in train.py but in test.py...? And anyone can help me solve this problem? Thanks a lot!!!

**Comment by eng100200** [comment]
@Poeroz  did you resolve? @leoxiaobin  i want to ask this line
writer_dict['writer'].add_graph(model, (dump_input, )) 
is also making problem in my train.py 
File "/home/anaconda3/envs/new_train/lib/python3.7/site-packages/torch/jit/__init__.py", line 1710, in __init__
    assert(isinstance(orig, torch.nn.Module))
AssertionError
giving assertion error,,,,not known why?

**Comment by eng100200** [comment]
@leoxiaobin how can i visualize the loss graph using tensorboard?

**Comment by Poeroz** [comment]
> @Poeroz did you resolve? @leoxiaobin i want to ask this line
> writer_dict['writer'].add_graph(model, (dump_input, ))
> is also making problem in my train.py
> File "/home/anaconda3/envs/new_train/lib/python3.7/site-packages/torch/jit/**init**.py", line 1710, in **init**
> assert(isinstance(orig, torch.nn.Module))
> AssertionError
> giving assertion error,,,,not known why?

Sorry I haven't resolved this problem yet...

**Comment by eng100200** [comment]
@Poeroz  may be @leoxiaobin  would help us!

**Comment by leoxiaobin** [comment]
Please check if the version of tensorboardX  is 1.6. If not, please try to re-install your tensorboardX==1.6. And then try again.

**Comment by Poeroz** [comment]
Thanks for your reply, finally I found maybe it’s because the version of
CUDA didn’t match the version of torch... When I change the CUDA to 9.0
everything went well. Anyway, thank you!

Leo Xiao <notifications@github.com>于2019年12月1日 周日23:55写道：

**Comment by eng100200** [comment]
@Poeroz @leoxiaobin i already installed tensorboard 1.6, but, do you mean tensorboardX ??

**Comment by eng100200** [comment]
@Poeroz i will also try cuda 9.0

**Comment by Poeroz** [comment]
Yeah, it is tensorboardX. You are using pytorch rather than tensorflow,
right?

eng100200 <notifications@github.com>于2019年12月2日 周一09:54写道：

**Comment by eng100200** [comment]
@Poeroz yes i am using pytorch

**Comment by eng100200** [comment]
pytorch 1.1.0 and 1.1.3

**Comment by leoxiaobin** [comment]
> @Poeroz @leoxiaobin i already installed tensorboard 1.6, but, do you mean tensorboardX ??

We use tensorboardX not tensorboard.

**Comment by Sakura-Mukira** [comment]
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/133#issuecomment-560239506
Can you tell me the version about pytorch and torchvision when you train,test and run demo ?
Thank you!

**Comment by eng100200** [comment]
@Sakura-Mukira i used pytorch 1.1.0 and torchvision 0.3.0

**Comment by Sakura-Mukira** [comment]
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/issues/133#issuecomment-612840291
@leoxiaobin what about you ?
@eng100200 can you run demo successfully use pytorch 1.1.0 and torchvision 0.3.0?

**Comment by Sakura-Mukira** [comment]
Thank you!

**Comment by yangsenius** [comment]
`None` in `nn.ModuleList` breaks the JIT in higher version of PyTorch. This problem is resolved by this issue pytorch/pytorch#30459.

**Comment by shubhambagwari** [comment]
Name: torch Version: 1.11.0+cu113
Name: torchvision Version: 0.12.0+cu113
